nohup: ignoring input
/tartarus/ianhy/github/general_test_granger_pipeline/general_granger_pipeline/SINK.py:46: RuntimeWarning: invalid value encountered in true_divide
  result = np.divide(np.real(r), (np.linalg.norm(x) * np.linalg.norm(y)))
11
0.90625 0.90625
0.9142857142857136 0.9021428571428568
0.9205357142857146 0.9081512188208618
0.9908928571428565 0.990209022317569
22
0.9196428571428571 0.9196428571428571
0.9303571428571421 0.9233035714285711
0.9285714285714289 0.9235866638321998
0.9933035714285706 0.9924280659569116
11
0.9151785714285714 0.9151785714285714
0.880357142857142 0.8655059523809522
0.8919642857142858 0.8810622165532882
0.9816071428571425 0.9798761338662816
22
0.9151785714285714 0.9151785714285714
0.9089285714285706 0.8930357142857137
0.8901785714285715 0.874139739229025
0.9881249999999994 0.9870769917199074
11
0.8928571428571429 0.8928571428571429
0.8892857142857136 0.8781547619047617
0.8982142857142861 0.8870897108843544
0.9830357142857135 0.981116862051478
22
0.9151785714285714 0.9151785714285714
0.9124999999999994 0.9014285714285712
0.9107142857142858 0.9021899801587304
0.9884821428571424 0.9863272409793239
11
0.9196428571428571 0.9196428571428571
0.8946428571428563 0.8803869047619043
0.8928571428571432 0.8788981009070299
0.9874107142857136 0.9864061135125841
22
0.9419642857142857 0.9419642857142857
0.9267857142857137 0.923035714285714
0.9250000000000006 0.918228812358277
0.9924999999999989 0.9917210601898322
11
0.9017857142857143 0.9017857142857143
0.8732142857142845 0.8555654761904757
0.8982142857142864 0.8829482001133792
0.9854464285714277 0.984029423634875
22
0.8839285714285714 0.8839285714285714
0.8946428571428564 0.881130952380952
0.9125000000000004 0.9041202522675741
0.9831249999999991 0.9820064049960541
11
0.9196428571428571 0.9196428571428571
0.9214285714285707 0.9140476190476187
0.9178571428571433 0.9092113095238098
0.9924107142857135 0.991202917995466
22
0.875 0.875
0.9160714285714279 0.9008630952380949
0.9098214285714288 0.8931519274376418
0.9934821428571423 0.9923688539992778
11
0.8839285714285714 0.8839285714285714
0.9285714285714279 0.9179464285714284
0.9196428571428577 0.909294217687075
0.9928571428571425 0.9918729468347364
22
0.9107142857142857 0.9107142857142857
0.910714285714285 0.9016369047619043
0.9178571428571435 0.9111713435374151
0.9839285714285708 0.982535184701282
11
0.8973214285714286 0.8973214285714286
0.8874999999999992 0.8699702380952379
0.9000000000000002 0.8870032596371888
0.9855357142857138 0.984466198418967
22
0.9241071428571429 0.9241071428571429
0.916071428571428 0.9026488095238092
0.9062500000000003 0.892619047619048
0.9921428571428567 0.9906403505683894
11
0.8571428571428571 0.8571428571428571
0.862499999999999 0.8481547619047618
0.8598214285714285 0.8494841269841272
0.9828571428571422 0.9807890391773745
22
0.7946428571428571 0.7946428571428571
0.8374999999999992 0.8145833333333331
0.8464285714285714 0.8311150085034014
0.9841964285714282 0.9815855061394165
11
0.8526785714285714 0.8526785714285714
0.8374999999999988 0.8188095238095229
0.8428571428571427 0.8291142290249435
0.9817857142857134 0.9795157459354753
22
0.84375 0.84375
0.8374999999999989 0.8161607142857138
0.8526785714285712 0.823673115079365
0.989999999999999 0.9884074213481119
11
0.84375 0.84375
0.8053571428571419 0.7874999999999994
0.8133928571428571 0.7901268424036278
0.9798214285714283 0.974928513022242
22
0.8214285714285714 0.8214285714285714
0.7982142857142847 0.7754761904761899
0.8142857142857144 0.7905077239229025
0.9860714285714278 0.984061326600887
11
0.8303571428571429 0.8303571428571429
0.801785714285713 0.77735119047619
0.8410714285714287 0.8216145833333336
0.9785714285714284 0.9734174601808128
22
0.8303571428571429 0.8303571428571429
0.7964285714285707 0.7752083333333329
0.808928571428571 0.792294501133787
0.9797321428571422 0.9742146853686947
11
Traceback (most recent call last):
  File "granger_pipeline.py", line 109, in <module>
    main()
  File "granger_pipeline.py", line 105, in main
    run_test(dataset_dict)
  File "granger_pipeline.py", line 79, in run_test
    brute_results, result_by_neighbor = general_test(causaldb, effectdb, trueMat, best_gamma = BEST_GAMMA, neighbor_param= NEIGHBORS,lag = lagged, pval=alpha_level)
  File "/tartarus/ianhy/github/general_test_granger_pipeline/general_granger_pipeline/Causal_Test.py", line 36, in general_test
    bruteMat = general_granger_matrix(Cause_TS,Effect_TS, lag,pval=pval)
  File "/tartarus/ianhy/github/general_test_granger_pipeline/general_granger_pipeline/Causal_inference.py", line 188, in general_granger_matrix
    gr_mat[i,j] = granger_causality(Effect_TS[j], Cause_TS[i], lag, pval=pval, check_one_lag=check_one_lag)
  File "/tartarus/ianhy/github/general_test_granger_pipeline/general_granger_pipeline/Causal_inference.py", line 72, in granger_causality
    res = grangercausalitytests(df, lag, verbose=False)
  File "/home/ianhy/.local/lib/python3.7/site-packages/statsmodels/tsa/stattools.py", line 1418, in grangercausalitytests
    "The Granger causality test statistic cannot be compute "
statsmodels.tools.sm_exceptions.InfeasibleTestError: The Granger causality test statistic cannot be compute because the VAR has a perfect fit of the data.
